<table id="tb_memexpr_rpt" border="1">
	<tr>
		<th>ลำดับ</th>
		<th>รหัส</th>
		<th>ชื่อ</th>
		<th>สาขา</th>
		<th>วันที่หมดอายุ</th>
		<th>สถานะ</th>
	</tr>
	{list}
	<tr>
		<td>{no}</td>
		<td>{code}</td>
		<td>{name}</td>
		<td>{branch}</td>
		<td>{expire_date}</td>
		<td>{status}</td>
	</tr>
	{/list}
</table>